db:
    image: mongo
    ports:
      - "27017:27017"
    command: "--smallfiles --logpath=/dev/null"
web:
    build: .
    command: "node -v"
    volumes:
        - ./app:/myapp
        - /myapp/node_modules
    links:
        - db